name: rr_frontend
description: Rewards & Recognition System Frontend
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
